function order = gen_zigzag4(x, tx_type, filename)

file=fopen(filename, 'a');

%Construct bands
B = ones(4,4);
B(1,1)=0;
#imagesc(B);

order=[];
for k=1:1
   mask = B==k;
   [dummy,ind]=sort(-x.*mask'(:));
   order = [order;ind(1:sum(sum(mask)))];
end
%start indexing at 0
order = order-1;

tx_names = ["DCT_DCT"; "ADST_DCT"; "DCT_ADST"; "ADST_ADST"];
tx_name = cellstr(tx_names);

fprintf(file, "/* This file is generated by gen_zigzag4.m */\n");
fprintf(file, "#include \"odintrin.h\"\n");
fprintf(file, "OD_EXTERN const unsigned char OD_ZIGZAG4_%s[%d][2] = {\n  ", 
  tx_name{tx_type + 1}, length(order));

for k=1:length(order)
   fprintf(file, "{%d, %d}", mod(order(k),4), floor(order(k)/4));
   if (k!=length(order))
      fprintf(file, ",");
   end
   if (mod(k,4)==0)
      fprintf(file, "\n  ");
   else
      fprintf(file, " ");
   end
end
fprintf(file, "};\n");

fclose(file);
