function order = gen_zigzag16(x, tx_type, filename)

file=fopen(filename, 'a');

%Construct bands
B = 3*ones(16,16);
B(1:8,1:8)=0;
B(1:4,9:16)=1;
B(9:16,1:4)=2;
#imagesc(B);

order=[];
for k=1:3
   mask = B==k;
   [dummy,ind]=sort(-x.*mask'(:));
   order = [order;ind(1:sum(sum(mask)))];
end
%start indexing at 0
order = order-1;

tx_names = ["DCT_DCT"; "ADST_DCT"; "DCT_ADST"; "ADST_ADST"];
tx_name = cellstr(tx_names);

fprintf(file, "/* This file is generated by gen_zigzag16.m */\n");
fprintf(file, "#include \"odintrin.h\"\n");
fprintf(file, "OD_EXTERN const unsigned char OD_ZIGZAG16_%s[%d][2] = {\n  ", 
  tx_name{tx_type + 1}, length(order));
  
for k=1:length(order)
   fprintf(file, "{%d, %d}", mod(order(k),16), floor(order(k)/16));
   if (k!=length(order))
      fprintf(file, ",");
   end
   if (mod(k,4)==0)
      fprintf(file, "\n  ");
   else
      fprintf(file, " ");
   end
end
fprintf(file, "};\n");

fclose(file);
